// import { Inter } from "next/font/google";
import "../styles/main.scss";
import Providers from "@/context/Providers";
import { ThemeModeScript } from "flowbite-react";
import { GeistSans } from "geist/font/sans";

// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "multi",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="light " style={{ colorScheme: "light" }}>
      <head>
        <ThemeModeScript />
      </head>
      <body className={GeistSans.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
